### ISSUE TITLE
Think I found a bug

### ISSUE THREAD

**Issue by burkejay** [r-simmer/simmer#4] opened 2015-05-05 18:07 UTC
Thanks so much for making this library; it really helped me out.

I created a resource with a maximum of 20 and the seize and release are both 1.  I "simmer" with 100 iterations.  When I do a get_resource_serve_mon_values and look at the resource, the value column should always go up or down by 1.  Every time I run it, I get just a few dozen instances where the resources in use will be 20, and instead of making the next entity wait, when it goes to use the last resource, the value count jumps to 39.

Here is the output of iteration 2 from get_resource_serve_mon_values:
![image](https://cloud.githubusercontent.com/assets/10569736/7479459/605d6ec8-f327-11e4-88fa-d3ca476b972e.png)

Here is a chart showing the jumps up to 39 and down:
![image](https://cloud.githubusercontent.com/assets/10569736/7479377/e17aede2-f326-11e4-809e-1c84f39a1319.png)

If you would be willing to take a look at it for me, could I share my code with you privately?  I will e-mail you my code.

**Comment by Enchufa2** [comment] 2015-05-05 18:22
Indeed, this is weird. Probably, there are more than one bug because of my last additions to the library. :-\ It would be great if you can paste a snippet of code here to reproduce this bug.

**Comment by burkejay** [comment] 2015-05-05 19:55
I would be happy to e-mail the code to you privately.  I e-mailed it to
Bart already.

**Comment by burkejay** [comment] 2015-05-11 20:09
Enchufa2,

Were you able to get my code from Bart?  If not, I guess I can change the numbers and post it.

**Comment by bart6114** [comment] 2015-05-12 07:31
HI all, sorry I've been on vacation so it took me a while to get to this.

@burkejay I can reproduce the bug here. Would it be possible to 'anonymize' it so you could share it here publicly?

I'm not sure whether the bug is actually in the resource allocation or in the monitoring functions. The `get_resource_serve_mon_values` function has been added recently after some (much needed) additions by @Enchufa2. So I'll have to browse to the code a bit to find the bug, the minimal example will help a bunch.

**Comment by Enchufa2** [comment] 2015-05-12 12:44
@burkejay Please, change whatever you need and share it here.

@Bart6114 Welcome back! [Here it is a simple event simulator of my own](http://www.it.uc3m.es/iucar/tr/04-R-en.html) and some examples that may help us test simmer.

**Comment by burkejay** [comment] 2015-05-12 20:38
Sorry, I had to take all the numbers out.  Hopefully, what I e-mailed is sufficient to find the bug.  I think what I e-mailed is the minimal example.

t1 <- create_trajectory("p") %>% add_seize_event("t", 1.0) %>% add_timeout_event("rnorm(1,2,1)") %>% add_skip_event(number_to_skip = "sample(c(0,4,8,12,16),1,FALSE,c(0.05,0.1,0.15,0.3,0.4))") %>% add_seize_event("e", 4.0) %>% add_timeout_event("rnorm(x,y,z)") %>% add_release_event("e", 4.0) %>% add_skip_event(number_to_skip ="12") %>% add_seize_event("e", 3.0) %>% add_timeout_event("rnorm(x,y,z)") %>% add_release_event("e", 3.0) %>% add_skip_event(number_to_skip ="8") %>% add_seize_event("e", 2.0) %>% add_timeout_event("rnorm(x,y,z)") %>% add_release_event("e", 2.0) %>% add_skip_event(number_to_skip ="4") %>% add_seize_event("e", 1.0) %>% add_timeout_event("rnorm(x,y,z)") %>% add_release_event("e", 1.0) %>% add_skip_event(number_to_skip ="0") %>% add_timeout_event("rnorm(1,2,1)") %>% add_release_event("t", 1.0)
sim <- create_simulator("psim", n = 100, until = 180) %>% add_resource("t", 20) %>% add_resource("e", 30)
sim <- sim %>% add_entities_with_interval(trajectory = t1, n = fo, name_prefix = "a", interval = "rnorm(x, y, z)")
sim <- sim %>% add_entities_with_interval(trajectory = t1, n = sf, name_prefix = "b", interval = "rnorm(x, y, z)")
sim <- sim %>% simmer()

**Comment by Enchufa2** [comment] 2015-10-12 18:36
Sorry, we cannot reproduce the bug without the values `x`, `y`, `z`, `fo` and `sf`. Can you provide us with some numbers, please?

**Comment by Enchufa2** [comment] 2015-10-12 18:58
BTW, I've just realised that we are allowing negative durations in the `add_timeout_event()` function and, obviously, this is a potentially fatal error. And `rnorm(1,2,1)` sometimes produces a negative value.

**Comment by burkejay** [comment] 2015-10-12 19:50
t1 <- create_trajectory("p") %>% add_seize_event("s", 1.0) %>%
add_timeout_event("rnorm(1,10,5)") %>% add_skip_event(number_to_skip =
"sample(c(0,4,8,12,16),1,FALSE,c(0.05,0.1,0.15,0.3,0.4))") %>%
add_seize_event("st", 4.0) %>% add_timeout_event("rnorm(1,12,6)") %>%
add_release_event("st", 4.0) %>% add_skip_event(number_to_skip ="12") %>%
add_seize_event("st", 3.0) %>% add_timeout_event("rnorm(1,12,6)") %>%
add_release_event("st", 3.0) %>% add_skip_event(number_to_skip ="8") %>%
add_seize_event("st", 2.0) %>% add_timeout_event("rnorm(1,12,6)") %>%
add_release_event("st", 2.0) %>% add_skip_event(number_to_skip ="4") %>%
add_seize_event("st", 1.0) %>% add_timeout_event("rnorm(1,12,6)") %>%
add_release_event("st", 1.0) %>% add_skip_event(number_to_skip ="0") %>%
add_timeout_event("rnorm(1,2,1)") %>% add_release_event("s", 1.0)
sim <- create_simulator("p_sim", n = 100, until = 180) %>%
add_resource("s", 20) %>% add_resource("st", 20)
sim <- sim %>% add_entities_with_interval(trajectory = t1, n = 51,
name_prefix = "coc", interval = "rnorm(1, 3.53, 0.5)")
sim <- sim %>% add_entities_with_interval(trajectory = t1, n = 75,
name_prefix = "eic", interval = "rnorm(1, 2.4, 0.4)")
sim <- sim %>% simmer()
t4 <- get_resource_serve_mon_values(sim,"s")
t5 <- get_resource_serve_mon_values(sim,"st")
t4_peak <- t4[t4$time > 60 & t4$time < 120,]
quantile(t4_peak$value, na.rm = TRUE, prob = seq(0, 1, length = 21))
t5_peak <- t5[t5$time > 60 & t5$time < 120,]
quantile(t5_peak$value, na.rm = TRUE, prob = seq(0, 1, length = 21))

**Comment by Enchufa2** [comment] 2015-10-12 21:19
Thanks. I see... Besides the negative duration problem that I mentioned before, this bug is difficult to fix with the current entity-based simulation core. We need to rebuild the package and transform the core into an event-based one.

**Comment by bart6114** [comment] 2015-10-14 13:55
I second @Enchufa2's suggestion, will start working on this asap (read coming weeks)...

**Comment by Enchufa2** [comment] 2015-11-13 14:44
@burkejay We have completely redesigned simmer and we are planning to submit it to CRAN. This bug report does not apply anymore, so we are going to close it. You are kindly invited to try the new version and to submit new bug reports. ;-)

**Closed as completed** 2015-11-13 14:44 UTC
